// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSettingsOrAppend(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ReadSettings():Promise<string>;

export function RemoveSettings(arg1:number):Promise<string>;
