// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSettingsOrAppend(arg1) {
  return window['go']['main']['App']['CreateSettingsOrAppend'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function RemoveSettings(arg1) {
  return window['go']['main']['App']['RemoveSettings'](arg1);
}
